apiVersion: apps/v1
kind: Deployment
metadata:
  name: hs-in1
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      hs: service
  template:
    metadata:
      labels:
        hs: service
    spec:
      containers:
      - name: hs-site
        image: hashservice:1.0
---
apiVersion: v1
kind: Service
metadata:
  name: hs-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    hs: service
  ports:
  - port: 5701
    targetPort: 5701
    nodePort: 30001


