// Code generated by protoc-gen-go. DO NOT EDIT.
// source: UserLogin.proto

package y_wcity

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	HashPassword         string   `protobuf:"bytes,2,opt,name=hashPassword,proto3" json:"hashPassword,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRequest) Reset()         { *m = UserRequest{} }
func (m *UserRequest) String() string { return proto.CompactTextString(m) }
func (*UserRequest) ProtoMessage()    {}
func (*UserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_62064063b9af919c, []int{0}
}

func (m *UserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRequest.Unmarshal(m, b)
}
func (m *UserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRequest.Marshal(b, m, deterministic)
}
func (m *UserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRequest.Merge(m, src)
}
func (m *UserRequest) XXX_Size() int {
	return xxx_messageInfo_UserRequest.Size(m)
}
func (m *UserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserRequest proto.InternalMessageInfo

func (m *UserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserRequest) GetHashPassword() string {
	if m != nil {
		return m.HashPassword
	}
	return ""
}

func (m *UserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UserResponse struct {
	IsUser               bool     `protobuf:"varint,1,opt,name=IsUser,proto3" json:"IsUser,omitempty"`
	Cookie               string   `protobuf:"bytes,2,opt,name=cookie,proto3" json:"cookie,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_62064063b9af919c, []int{1}
}

func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (m *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(m, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetIsUser() bool {
	if m != nil {
		return m.IsUser
	}
	return false
}

func (m *UserResponse) GetCookie() string {
	if m != nil {
		return m.Cookie
	}
	return ""
}

func init() {
	proto.RegisterType((*UserRequest)(nil), "y_wcity.UserRequest")
	proto.RegisterType((*UserResponse)(nil), "y_wcity.UserResponse")
}

func init() { proto.RegisterFile("UserLogin.proto", fileDescriptor_62064063b9af919c) }

var fileDescriptor_62064063b9af919c = []byte{
	// 250 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x0f, 0x2d, 0x4e, 0x2d,
	0xf2, 0xc9, 0x4f, 0xcf, 0xcc, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xaf, 0x8c, 0x2f,
	0x4f, 0xce, 0x2c, 0xa9, 0x54, 0x8a, 0xe6, 0xe2, 0x06, 0xc9, 0x05, 0xa5, 0x16, 0x96, 0xa6, 0x16,
	0x97, 0x08, 0x89, 0x70, 0xb1, 0xa6, 0xe6, 0x26, 0x66, 0xe6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70,
	0x06, 0x41, 0x38, 0x42, 0x4a, 0x5c, 0x3c, 0x19, 0x89, 0xc5, 0x19, 0x01, 0x89, 0xc5, 0xc5, 0xe5,
	0xf9, 0x45, 0x29, 0x12, 0x4c, 0x60, 0x49, 0x14, 0x31, 0x21, 0x21, 0x2e, 0x96, 0xbc, 0xc4, 0xdc,
	0x54, 0x09, 0x66, 0xb0, 0x1c, 0x98, 0xad, 0x64, 0xc7, 0xc5, 0x03, 0x31, 0xbc, 0xb8, 0x20, 0x3f,
	0xaf, 0x38, 0x55, 0x48, 0x8c, 0x8b, 0xcd, 0xb3, 0x18, 0x24, 0x02, 0x36, 0x9e, 0x23, 0x08, 0xca,
	0x03, 0x89, 0x27, 0xe7, 0xe7, 0x67, 0x67, 0xa6, 0x42, 0x4d, 0x86, 0xf2, 0x8c, 0x5a, 0x19, 0xb9,
	0x84, 0x40, 0x0a, 0x1c, 0x4b, 0x4b, 0x32, 0x52, 0xf3, 0x4a, 0x32, 0x93, 0x13, 0x4b, 0x32, 0xf3,
	0xf3, 0x84, 0x2c, 0xb8, 0x38, 0x9d, 0x33, 0x52, 0x93, 0xb3, 0xc1, 0x7a, 0x45, 0xf4, 0xa0, 0x5e,
	0xd1, 0x43, 0xf2, 0x87, 0x94, 0x28, 0x9a, 0x28, 0xd4, 0x01, 0xa6, 0x5c, 0x6c, 0xce, 0x45, 0xa9,
	0x89, 0x25, 0xa9, 0x24, 0x69, 0x73, 0xd2, 0xe5, 0x12, 0xce, 0xcc, 0xd7, 0x4b, 0x2f, 0x2a, 0x48,
	0xd6, 0x83, 0xc8, 0xe6, 0x80, 0x82, 0xd2, 0x89, 0x0f, 0x1e, 0xaa, 0x01, 0xa0, 0x40, 0x0d, 0x60,
	0x5c, 0xc4, 0xc4, 0x1c, 0x14, 0xe0, 0x9c, 0xc4, 0x06, 0x0e, 0x63, 0x63, 0x40, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x56, 0x66, 0x5b, 0x0e, 0x76, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserAuthenticationClient is the client API for UserAuthentication service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserAuthenticationClient interface {
	CheckUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserResponse, error)
	Create(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserResponse, error)
}

type userAuthenticationClient struct {
	cc *grpc.ClientConn
}

func NewUserAuthenticationClient(cc *grpc.ClientConn) UserAuthenticationClient {
	return &userAuthenticationClient{cc}
}

func (c *userAuthenticationClient) CheckUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/y_wcity.UserAuthentication/CheckUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAuthenticationClient) Create(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/y_wcity.UserAuthentication/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserAuthenticationServer is the server API for UserAuthentication service.
type UserAuthenticationServer interface {
	CheckUser(context.Context, *UserRequest) (*UserResponse, error)
	Create(context.Context, *UserRequest) (*UserResponse, error)
}

// UnimplementedUserAuthenticationServer can be embedded to have forward compatible implementations.
type UnimplementedUserAuthenticationServer struct {
}

func (*UnimplementedUserAuthenticationServer) CheckUser(ctx context.Context, req *UserRequest) (*UserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckUser not implemented")
}
func (*UnimplementedUserAuthenticationServer) Create(ctx context.Context, req *UserRequest) (*UserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}

func RegisterUserAuthenticationServer(s *grpc.Server, srv UserAuthenticationServer) {
	s.RegisterService(&_UserAuthentication_serviceDesc, srv)
}

func _UserAuthentication_CheckUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAuthenticationServer).CheckUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/y_wcity.UserAuthentication/CheckUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAuthenticationServer).CheckUser(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserAuthentication_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAuthenticationServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/y_wcity.UserAuthentication/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAuthenticationServer).Create(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserAuthentication_serviceDesc = grpc.ServiceDesc{
	ServiceName: "y_wcity.UserAuthentication",
	HandlerType: (*UserAuthenticationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckUser",
			Handler:    _UserAuthentication_CheckUser_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _UserAuthentication_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "UserLogin.proto",
}
